/* Automatically generated by po2tbl.sed from ixlib.pot.  */

#if HAVE_CONFIG_H
# include <config.h>
#endif

#include "libgettext.h"

const struct _msg_ent _msg_tbl[] = {
  {"", 1},
  {"Unable to evaluate expression", 2},
  {"Function not yet implemented", 3},
  {"General error", 4},
  {"NULL pointer encountered", 5},
  {"Invalid parameter", 6},
  {"Index out of range", 7},
  {"Buffer overrun", 8},
  {"Buffer underrun", 9},
  {"Item not found", 10},
  {"Invalid operation", 11},
  {"Dimension mismatch", 12},
  {"Operation cancelled", 13},
  {"Unable to allocate memory", 14},
  {"Unmatched wildcard", 15},
  {"Parameter error: wildcard", 16},
  {"Path syntax error", 17},
  {"Path relative or invalid", 18},
  {"Seek error", 19},
  {"Read request across EOF", 20},
  {"Write request across EOF", 21},
  {"Write protection violation", 22},
  {"File clipping violation", 23},
  {"Internal error", 24},
  {"No such file or directory", 25},
  {"Access denied", 26},
  {"File exists", 27},
  {"Too many open files", 28},
  {"Out of media space", 29},
  {"File too big", 30},
  {"Hardware failure", 31},
  {"Path inaccessible", 32},
  {"Continuity violation", 33},
  {"Not supported", 34},
  {"Invalid file format", 35},
  {"Invalid replacement sequence", 36},
  {"Invalid chunk", 37},
  {"CRC error", 38},
  {"Invalid quantifier", 39},
  {"Unbalanced backreference", 40},
  {"Invalid escape sequence", 41},
  {"Invalid backreference", 42},
  {"Unterminated character class", 43},
};

int _msg_tbl_length = 43;
